---
title: "trendEcon"
output: 
  flexdashboard::flex_dashboard
---

```{r setup, include=FALSE}
library(openxlsx)
library(tidyverse)
library(data.table)
library(zoo)
library(dygraphs)
library(xts)

kons_SA_nom_q <- data.table(read.xlsx(file.path("kons_SA_csa_new.xlsx"),
                     sheet = "real_q",
                     startRow = 11))%>% 
  rename(year = V1, q = V2) %>% 
  select(., -starts_with("V")) %>% 
  pivot_longer(c(-year,-q), names_to = "ts") %>% 
  filter(!is.na(value)) %>% 
  pivot_wider(c(year,q), names_from = ts, values_from = value) %>% 
  mutate(date=as.Date(as.yearqtr(paste0(year, sep="-",q)))) %>% 
  data.frame() %>% 
  `row.names<-`(.,.$date) %>% 
  select(-date,-year,-q) %>% 
  as.xts()

```

Consumer expenditure
===================================== 
Column
-------------------------------------
    
### Chart 1
    
```{r}
dygraph(kons_SA_nom_q$kons, main = "Consumer expenditure")%>%
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 3)) %>% 
  dyAxis("x", drawGrid = FALSE)%>%
  dyLegend(show = "follow") %>% 
  dyRangeSelector()
```

Consumer expenditure by category
===================================== 

Row
-------------------------------------

### Food
    
```{r}
dygraph(kons_SA_nom_q["1995/2020",2], group="index")%>%
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 3)) %>% 
  dyAxis("x", drawGrid = FALSE)%>%
  dyLegend(width = 700)%>% 
  dyRangeSelector()
```
    
### Clothing

```{r}
dygraph(kons_SA_nom_q["1995/2020",3],group="index")%>%
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 3)) %>% 
  dyAxis("x", drawGrid = FALSE)%>%
  dyLegend(width = 700)%>% 
  dyRangeSelector()
```

### Housing

```{r}
dygraph(kons_SA_nom_q["1995/2020",4], group="index")%>%
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 3)) %>% 
  dyAxis("x", drawGrid = FALSE)%>%
  dyLegend(width = 700)%>% 
  dyRangeSelector()
```

Row
-------------------------------------
    
### Furniture
    
```{r}
dygraph(kons_SA_nom_q["1995/2020",5], group="index")%>%
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 3)) %>% 
  dyAxis("x", drawGrid = FALSE)%>%
  dyLegend(width = 700)%>% 
  dyRangeSelector()
```
    
### Health

```{r}
dygraph(kons_SA_nom_q["1995/2020",6], group="index")%>%
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 3)) %>% 
  dyAxis("x", drawGrid = FALSE)%>%
  dyLegend(width = 700)%>% 
  dyRangeSelector()
```

### Traffic

```{r}
dygraph(kons_SA_nom_q["1995/2020",7], group="index")%>%
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 3)) %>% 
  dyAxis("x", drawGrid = FALSE)%>%
  dyLegend(width = 700)%>% 
  dyRangeSelector()
```

Row
-------------------------------------
    
### Telecom
    
```{r}
dygraph(kons_SA_nom_q["1995/2020",8], group="index")%>%
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 3)) %>% 
  dyAxis("x", drawGrid = FALSE)%>%
  dyLegend(width = 700)%>% 
  dyRangeSelector()
```
    
### Entertainment

```{r}
dygraph(kons_SA_nom_q["1995/2020",9],group="index")%>%
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 3)) %>% 
  dyAxis("x", drawGrid = FALSE)%>%
  dyLegend(width = 700)%>% 
  dyRangeSelector()
```

### Education

```{r}
dygraph(kons_SA_nom_q["1995/2020",10], group="index")%>%
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 3)) %>% 
  dyAxis("x", drawGrid = FALSE)%>%
  dyLegend(width = 700)%>% 
  dyRangeSelector()
```

Row
-------------------------------------
    
### Hotel
    
```{r}
dygraph(kons_SA_nom_q["1995/2020",11], group="index")%>%
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 3)) %>% 
  dyAxis("x", drawGrid = FALSE)%>%
  dyLegend(width = 700)%>% 
  dyRangeSelector()
```
    
### Other

```{r}

dygraph(kons_SA_nom_q["1995/2020",12], group="index")%>%
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 3)) %>% 
  dyAxis("x", drawGrid = FALSE)%>%
  dyLegend(width = 700)%>% 
  dyRangeSelector()
```

### Pooe

```{r}
dygraph(kons_SA_nom_q["1995/2020",13], group="index")%>%
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 3)) %>% 
  dyAxis("x", drawGrid = FALSE)%>%
  dyLegend(width = 700)%>% 
  dyRangeSelector()
```